### ISSUE TITLE
Question about WithdrawDelegatorReward

### ISSUE THREAD

**Issue by tgrecojs** [eco-stake/restake#14]
Really awesome tech being built here! 🙂  

Going thru the readme and i had a question about the following sentence.

> REStake specifically lets you grant a validator permission to send WithdrawDelegatorReward and Delegate transactions for their validator only (note WithdrawDelegatorReward is technically not restricted to a single validator)

I'm very curious about the authority that users are handing over to validators by using restake so was wondering if someone add more clarity on the text in parenthesis? What are (if any) the implications of `WithdrawDelegatorReward` not being restricted to a single validator?

**Comment by tombeynon** [comment]
Hey @tgrecojs, great question and it does have an implication for the delegator.

The worst thing a validator could do currently if they adjusted the autostaking script is claim rewards from _all_ validators you delegate to, and then delegate your entire current balance + all rewards to themselves. REStake is currently intended for validators to only claim from themselves, and only use the pending reward balance, not the wallet balance, but it's a very soft limitation. You could however undelegate fairly quickly and revoke their permission when you noticed.

Unfortunately Authz doesn't allow me to restrict the withdraw address as far as I can tell.. yet. This will expand in the near future I'm sure.

The additional restrictions I am going to add to the UI soon are:

- Expiry date of the grant (currently 1 year but user can choose)
- Max amount of tokens the validator can delegate (currently unlimited but a max total can be set + update)

**Comment by tgrecojs** [comment]
Thanks for clarifying @tombeynon! 

> The worst thing a validator could do currently if they adjusted the autostaking script is claim rewards from all validators you delegate to, and then delegate your entire current balance + all rewards to themselves. 

Ah, i see. Can u clarify whether this permission that users grant validators with is restricted to a specific blockchain, or if a validator will be able to execute WithdrawDelegatorReward for all chains within the cosmos ecosystem that they r staking on? If it's the latter, then this seems to have some pretty serious implications 😬 

> REStake is currently intended for validators to only claim from themselves, and only use the pending reward balance, not the wallet balance, but it's a very soft limitation.

Seeing as people don't always acts as their supposed to, I'm more worried about what happens when un-intended use-cases arise. 🙂 

> Unfortunately Authz doesn't allow me to restrict the withdraw address as far as I can tell.. yet. This will expand in the near future I'm sure.

Nice! Hopefully in the near future Authz makes it possible to limit the amount of power that a user needs to hand over when using this module. I don't know much about it, but this has already been very helpful!

**Comment by tombeynon** [comment]
Resolved with #487 and #435
