### ISSUE TITLE
Error: Module not found

### ISSUE THREAD

**Issue by tpmmthomas** [eco-stake/restake#167]
Hi, I am trying to become an operator of restake but I am not able to run the docker image successsfully.
I already have latest docker and docker-compose installed on an Ubuntu machine.
When I run `sudo docker-compose run --rm app npm run autostake`, the following error occurs:

`
> restake@0.1.0 autostake
> node scripts/autostake.mjs

node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@cosmjs/proto-signing' imported from /usr/src/app/scripts/autostake.mjs
    at new NodeError (node:internal/errors:372:5)
    at packageResolve (node:internal/modules/esm/resolve:907:9)
    at moduleResolve (node:internal/modules/esm/resolve:956:20)
    at defaultResolve (node:internal/modules/esm/resolve:1172:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v17.7.1
ERROR: 1
`
May I know how to resolve this problem? Thank you.

**Comment by iprouteth0** [comment]
I can confirm this, I get the same result

![Screenshot_20220314-233145-305](https://user-images.githubusercontent.com/7662947/158308443-4da7a443-ecd8-4e1e-b7ae-158abf3be092.png)

**Comment by tombeynon** [comment]
If you run `docker-compose build` does that resolve it?

**Comment by tpmmthomas** [comment]
No, I tried running that `sudo docker-compose build` before  `sudo docker-compose run ...`, still fails.

**Comment by tombeynon** [comment]
Thanks I'm looking at this now

**Comment by chleeab** [comment]
Same here. Thanks for looking at this

**Comment by chleeab** [comment]
I get it work by installing the module manually then re-run docker-compose

**Comment by tombeynon** [comment]
This should now be fixed in master. 

```
git pull
docker-compose build --no-cache
```
