### ISSUE TITLE
Not updating data after redelegation

### ISSUE THREAD

**Issue by JoseCT-HS** [eco-stake/restake#269]
Some people have redelegated to validators through Keplr. In REStake, most of the chains shows this change but for the "Cosmos HUB" doesn't.

I've tried deleting the cache of my browser as sometimes it helps but it keeps showing that the delegation is still in the old validator. It also throws some errors if you try any other action through REStake.

P.D: I have not seen a similar issue related to this, sorry if this is a known issue

**Comment by tombeynon** [comment]
Thanks - the public cosmoshub node that REStake uses is stalled right now, so it's showing old data. I'm going to add a warning to the site for this ASAP, and the node should be back up and running soon.
