### ISSUE TITLE
Not restaked eventhough already reach min rewards at CosmosHub

### ISSUE THREAD

**Issue by infobkl** [eco-stake/restake#274]
Rewards already >0.01 at Keplr. But it keeps <0.01 at restake.app. 

![image](https://user-images.githubusercontent.com/101842753/158912040-eaf88c36-2403-429c-bf89-5b618a77e895.png)

![image](https://user-images.githubusercontent.com/101842753/158912107-f78edea1-c2f1-4a56-be82-6eafeab477fb.png)

**Comment by tombeynon** [comment]
The CosmosHub node has stalled, so what you're seeing in REStake is behind by a day. I'm just deploying a fix now which will show an error message, and hopefully the node will be fixed soon. 

Your compounding will likely still happen in the background :)

**Comment by infobkl** [comment]
can't connect

![image](https://user-images.githubusercontent.com/101842753/158923337-6b2d3fbe-fee5-4d7b-a1d4-67ee1364c7b6.png)
