### ISSUE TITLE
Manually compound multiple validators at the same time failes

### ISSUE THREAD

**Issue by bjaanes** [eco-stake/restake#340]
Because of the way the simulation is run it fails if you don't have a lot of funds (because the simulation uses totalReward as perValidatorReward, making the total numberOfValidators*totalReward).

Typical error message:
```
Failed to broadcast: Query failed with (18): failed to execute message; message index: 1: failed to delegate; 295611224ucrbrus is smaller than 559741054ucrbrus: insufficient funds: invalid request
```

The solution is to fix the simulation to create correct messages.

An additional part that can be tackled in this issue is also how perValidatorReward is currently naively calculated as totalReward/numberOfValidators. This spreads the reward equally among all validators, instead of re-delegating the amount each validator has 'saved' up.

**Comment by tombeynon** [comment]
Great work @bjaanes, in master
