### ISSUE TITLE
failed to enable restake in desmos

### ISSUE THREAD

**Issue by leonnipp** [eco-stake/restake#377]
When i trying to Failed to enable restake in desmos, it shows broadcast: Unsupported type: '/desmos.profiles.v1beta1.Profile'
![Screenshot 2022-03-28 at 10 15 24 PM](https://user-images.githubusercontent.com/42675642/160417712-c73972b3-4091-480c-8756-8d381bf68d25.png)

**Comment by tombeynon** [comment]
Duplicate of #334
