### ISSUE TITLE
Failed to connect getaddrinfo ENOTFOUND registry.undefined

### ISSUE THREAD

**Issue by alighasemzadeh** [eco-stake/restake#392]
Failed to connect getaddrinfo ENOTFOUND registry.undefined

I get this error when I run `npm run autostake`

**Comment by tombeynon** [comment]
You need to run `docker-compose build --no-cache` when you pull updates. I've just pushed a change which will set additional defaults for these variables though so that will also avoid this error. 

Leaving this open for a while in case others run into it

**Comment by alighasemzadeh** [comment]
I want to run without docker

**Comment by tombeynon** [comment]
If you pull latest it'll work without docker.

**Comment by tombeynon** [comment]
I use docker-compose, which supports the `.env` file detailed in the README. The `dotenv` package is similar but isn't part of REStake currently. I haven't had a chance to document the process for running it without Docker, so if you want to do that you're somewhat on your own right now.

As mentioned, all you need to do is set that environment variable before you run the script. There are many ways you can do that. But right now, I'd recommend using Docker unless you're familiar with doing it manually.

**Comment by alighasemzadeh** [comment]
I didi it.

my file: networks.local.json
````
{
  "bitsong": {
    "prettyName": "Winner",
    "autostake": {
      "correctSlip44": true, // Use the correct slip44 path from chain-registry
      "slip44": 852 // Alternatively set a specific slip44 path
    }
}
````

output:
[15:15:35.578] ⚛
[15:15:35.578] Starting BitSong
[15:15:35.585] Bot address is bitsong1qaa6nsq0g4zwkcpzt0tet7ntwrq2lt7yrpytdq
[15:15:35.585] !! You are not using the preferred derivation path !!
[15:15:35.586] !! You should switch to the correct path unless you have grants. Check the README !!
[15:15:35.586] Not an operator
[15:15:35.586] Skipping

**Comment by alighasemzadeh** [comment]
this is my networks.local.json
````
{
  "bitsong": {
    "prettyName": "Winner",
    "autostake": {
      "correctSlip44": true
    }
}
````

**Comment by tombeynon** [comment]
I'm not sure what else to suggest I'm afraid, I don't know how you've set this up. I do know that if a `src/networks.local.json` file exists it will be picked up by the script.

I'm going to close this issue, please reach out on Discord if you need more support.
