### ISSUE TITLE
get all grants associated to an account instead of delegators then grants

### ISSUE THREAD

**Issue by marbar3778** [eco-stake/restake#398]
https://github.com/cosmos/cosmos-sdk/pull/11523

After this is released it would be good to migrate to getting grants associated to a grantee instead of getting delegators and so on

**Comment by tombeynon** [comment]
Ah man finally!! This is the biggest challenge with REStake right now, it has to hit the nodes so many times to get the info it needs. I figured an endpoint like this was coming but wasn't tracking anything specific. 

Thank you, will implement as soon as it's available

**Comment by marbar3778** [comment]
ill try to get it released in the coming days, if not today

**Comment by marbar3778** [comment]
This was recently merged and some chains should start seeing it
