### ISSUE TITLE
Missing 'dotenv' package causes restake to fail

### ISSUE THREAD

**Issue by SecretSaturn** [eco-stake/restake#402]
When trying to run (of course after recompiling with "sudo docker-compose build --no-cache") restake I get the following error with the new version (0.6.3), older versions did not have this: 

> node:internal/errors:465
>     ErrorCaptureStackTrace(err);
>     ^
> 
> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'dotenv' imported from /usr/src/app/scripts/base.mjs

**Comment by tombeynon** [comment]
Ah annoying. I'm going to improve the update process in general, it's a pain right now. The following should fix it:

```
sudo docker-compose run --rm app npm install
```

**Comment by SecretSaturn** [comment]
Thanks, that fixed it 👍
