### ISSUE TITLE
Error: Given amount is not a safe integer

### ISSUE THREAD

**Issue by zaunermax** [eco-stake/restake#410]
When using the [fetchub part](https://restake.app/fetchhub) of the web app I got following error:

My amount was not a float or comma number it was actually something like `100`

![image](https://user-images.githubusercontent.com/15246773/161857705-b21364f9-a007-4f2b-a5ba-802b30ac11ee.png)

Thanks for creating this amazingly cool webapp :raised_hands:

**Comment by tombeynon** [comment]
Ah thank you, same issue that Sifchain has #133. I'll look at this asap ❤️

**Comment by mcanvar** [comment]
Hello, I've got this also while running `Fetch.io`:
`Failed to get address Given amount is not a safe integer. Consider using a string instead to overcome the limitations of JS numbers.`

My question is can we use min reward amount as a string in chains.json:
from
`"minimum_reward": 100000000000000000`
to
`"minimum_reward": "100000000000000000"`

Thank you for your wonderful work.

**Comment by tombeynon** [comment]
@mcanvar with the changes in #424 you can set a string minimumReward - that will be handled now along with other fixes for these chains.

**Comment by mcanvar** [comment]
@tombeynon great thanks!
