### ISSUE TITLE
Error with custom RPCs/LCDs: "Failed to connect el.match is not a function"

### ISSUE THREAD

**Issue by iicc1** [eco-stake/restake#426]
Hello,
I recently started to see errors in the networks where I have custom RPCs/LCDs configured.

This is my `networks.local.json` file:
```
{
  "cryptoorgchain": {
    "restUrl": [
      "http://xxx:yyy"
    ],
    "rpcUrl": [
      "http://xxx:yyy"
    ]
 },
 "terra": {
   "restUrl": [
      "https://terra-lcd.stakely.io"
    ],
    "rpcUrl": [
      "https://terra-rpc.stakely.io"
    ]
 },
 "cosmoshub": {
    "restUrl": [
      "https://cosmoshub-lcd.stakely.io"
    ],
    "rpcUrl": [
      "https://cosmoshub-rpc.stakely.io"
    ]
  },
  "secretnetwork": {
    "gasPrice": "0.25uscrt"
  },
  "desmos": {
    "gasPrice": "0.01udsm"
  }
}
```
The JSON file seems to be fine and has been working properly for weeks.

This is the error I get with the networks I have with custom providers (cryptoorgchain, terra, cosmoshub)
```
 Failed to connect el.match is not a function
```

Many thanks in advance

**Comment by tombeynon** [comment]
Hey sorry an update broke this but it was fixed last night. Latest master should solve it

**Comment by iicc1** [comment]
Many thanks, I just updated the code and it is working fine again.
Keep up the great work
