### ISSUE TITLE
autostake script fails on cosmoshub due to api rate limits or rpc load

### ISSUE THREAD

**Issue by clemensgg** [eco-stake/restake#44]
hi, thanks again for this!! what i encountered running the autostake script on cosmoshub:

## scenario 1: RPC load makes connected node fall back

the script fails because at a point the node is not able to broadcast txs:

```sh
Found 7 delegators with valid grants...
cosmos... uatom reward is too low, skipping
cosmos... 892 uatom reward is too low, skipping
cosmos... 576 uatom reward is too low, skipping
cosmos... Autostaking 297743 uatom
cosmos... Successfully broadcasted
cosmos... 980 uatom reward is too low, skipping
cosmos... Autostaking 94897 uatom
cosmos... Successfully broadcasted
cosmos... Autostaking 14823 uatom
cosmos... Failed to broadcast: TimeoutError: Transaction with ID 3B1E27CF726851E2918ABEFB3D5FCAA4FF34F12AD35C618FB40F324AF7EA2E8D was submitted but was not yet found on the chain. You might want to check later.
    at pollForTx (/home/osmo/restake/node_modules/@cosmjs/stargate/build/stargateclient.js:213:23)
    at pollForTx (/home/osmo/restake/node_modules/@cosmjs/stargate/build/stargateclient.js:226:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  txId: '3B1E27CF726851E2918ABEFB3D5FCAA4FF34F12AD35C618FB40F324AF7EA2E8D'
}
```

this is common behaviour of heavy chain nodes, if RPC load is high the node will start lagging and fall out of sync, to catch up as soon as the load lowers significantly. We're experiencing this regularly on our relayer endpoints on various chains, but cosmoshub is the most prone to that error.

transactions "stuck" in this way will eventually be broadcasted to the mempool and confirm on-chain, but only if the node is able to reach the tip

_proposed solution: batch txs (?); make broadcast TimeoutError non critical_

_workaround: repeatedly run script with chain argument until there are no errors anymore_

---

## scenario 2: LCD hits rate-limit:

the current connected public lcd hits some limit and times out:

```sh
path: '/cosmos/staking/v1beta1/validators/cosmosvaloper14qazscc80zgzx3m0m0aa30ths0p9hg8vdglqrc/delegations?pagination.limit=1000',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'lcd-cosmoshub.blockapsis.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: '<html>\r\n' +
      '<head><title>504 Gateway Time-out</title></head>\r\n' +
      '<body>\r\n' +
      '<center><h1>504 Gateway Time-out</h1></center>\r\n' +
      '</body>\r\n' +
      '</html>\r\n'
  },
  isAxiosError: true
```

_proposed solution: validators providing the service could use private REST endpoints without rate limits_

while these errors turned up during tests on cosmoshub it doesn't mean they are limited to the hub, it can be assumed that the bigger the number of total delegators, the worse the load issues will be

**Comment by tombeynon** [comment]
Awesome detail, thanks so much! I updated the script last night around this sort of thing but it won't affect any of these specific issues. 

1st one.. should be okay to skip to the next address when this happens but need to work out the error checking. 

2nd - There's a draft PR for batching the delegations (on mobile atm) which I'm going to finish up to pull the delegations in batches to get all (hard capped at 1k atm), so I'll reduce the page size and hopefully solve this one. 

Great idea about private nodes, can pass that in as an argument to the script. Only needs a single one each run I assume 

Updates coming asap.

**Comment by clemensgg** [comment]
awesome tysm! 

looking over it that should have been two issues, you want me to open another one?

**Comment by tombeynon** [comment]
Not at all, this is perfect

**Comment by tombeynon** [comment]
Between the cosmoshub fee increase and performance tweaks in the autostaking script, hopefully this is mitigated. I'm going to close this for now but please reopen if it comes up again.
