### ISSUE TITLE
"Invalid" on grant page when the grants are correct

### ISSUE THREAD

**Issue by Freak12Techno** [eco-stake/restake#443]
I have the following displayed on my validator's page for my wallet I have grants for:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/83376337/163688854-52b60fe6-e941-4066-bf65-f152160a52ba.png">

My grants are the following:
```
[
    {
        "authorization": {
            "@type": "/cosmos.authz.v1beta1.GenericAuthorization",
            "msg": "/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward"
        },
        "expiration": "2023-04-16T14:41:59Z"
    },
    {
        "authorization": {
            "@type": "/cosmos.authz.v1beta1.GenericAuthorization",
            "msg": "/cosmos.staking.v1beta1.MsgDelegate"
        },
        "expiration": "2023-04-16T14:45:47Z"
    }
]
```
so it should be all valid (no limitation on sum or , yet somehow it says it isn't. What may be the reason for?
I tried to see the source for this error, this line https://github.com/eco-stake/restake/blob/7c2b8edece6a1860db798332d064c42d9c1809f8/src/utils/OperatorGrants.mjs#L46 sounds suspicious (as there's no `validators` declared, only `grantValidators`), but I can't confirm or deny it's the reason.
Can you look into it?
Thanks in advance!

**Comment by tombeynon** [comment]
Hey sorry about this, working on it in #442. The grants are valid, it's just the display which is incorrect right now

**Comment by Freak12Techno** [comment]
Got it, thanks!
I guess you may close this one as a duplicate if you like, as there's already an ongoing issue on that.
