### ISSUE TITLE
Stargaze page do not show APR

### ISSUE THREAD

**Issue by chleeab** [eco-stake/restake#453]
![image](https://user-images.githubusercontent.com/88308388/163923444-3e5a17b6-3f34-42bc-9fca-bf0fb8f8c387.png)

Is it a bug?

**Comment by tombeynon** [comment]
Intentional for now I'm afraid, the on-chain way of calculating inflation doesn't work with Stargaze and a few others. Will leave this open for now.

**Comment by tombeynon** [comment]
Resolved in #541
