### ISSUE TITLE
Manual compound is failing for IXO (insufficient fee)

### ISSUE THREAD

**Issue by bjaanes** [eco-stake/restake#455]
Seems like the fee calculations for IXO is not working properly

> Failed to broadcast: Broadcasting transaction failed with code 13 (codespace: sdk). Log: insufficient fees; got: 6901uixo required: 27604uixo: insufficient fee

![image](https://user-images.githubusercontent.com/1344105/164177877-694ce353-1d83-4184-aa79-359bc1332232.png)

Even the high fee option is not sufficient.

![image](https://user-images.githubusercontent.com/1344105/164178396-5ffbc9b5-f798-4292-b402-300de40fcaa8.png)

**Comment by tombeynon** [comment]
@bjaanes do you know if this was working before?

We'll need to set custom gas prices for Keplr, as done for AssetMantle here: https://github.com/eco-stake/restake/blob/master/src/networks.json#L195-L199

**Comment by bjaanes** [comment]
@tombeynon Honestly I am not sure. It hasn't been working for a while I think.

I tried changing the settings both with and without `gasPriceStep`. It just doesn't seem to take. When I debug I can see an updated fee being sent
```javascript
console.log("fee", fee); // Shows an updated higher fee
client.signAndBroadcast(address, msgs, fee, memo).then((result) => {
...
```

```json
  {
    "name": "impacthub",
    "gasPrice": "0.05uixo",
    "gasPriceStep": {
      "low": 0.025,
      "average": 0.05,
      "high": 0.1
    },
    "authzSupport": false
  },
```

I am not able to figure out how the `gasPriceStep` is sent either. I assume it is supposed to override the default config from keplr, but I am finding out how :D

**Comment by tombeynon** [comment]
That'll do it - I find it the networks.json caches quite heavily locally, particularly when changing that attribute weirdly.. it overrides in the suggestChain function.

I'll add this change in now, it's probably just a public node with higher than usual gas fees which needs solving properly, but at least 0.1 will give them the option. Numbers look right in your error.

**Comment by tombeynon** [comment]
So this is more challenging 😂 

gasPriceStep is used for suggestChain, so only when you add the chain for the first time. Didn't realise IXO was a chain native to Keprl so we can't set the gas price options. We can override the gas price for the TX (user then has to click 'override fee' to get back to the 3 options), but it doesn't make sense to set this at 4x the recommended min gas price for one node. 

So... only real option we have is find a way to remove that node from cosmos.directory, re: #432. Or we add a gas price config in the UI which is then used to override Keplr options. I'm possibly leaning towards the UI option as Keplr is very limited in this regard atm, and I'm not aware of a way to determine the gas prices for a given node.
