### ISSUE TITLE
Not being able to add a chain not supported by ReStake officially

### ISSUE THREAD

**Issue by freak12techno** [eco-stake/restake#479]
So I have a validator now on Provenance chain and I want to enable ReStake support there. I added the following to `src/networks.local.json`:

```
  "provenance": {
    "autostake": {
      "slip44": 505
    }
  },
```

Then I run restake command and I get this error:
```
monitoring@hetzner-monitoring:~/restake$ docker-compose run --rm app npm run autostake
Creating restake_app_run ... done

> restake@0.1.0 autostake
> node scripts/autostake.mjs

[09:05:54.181] Invalid key in networks.local.json: provenance
... rest is omitted
```

What should I do to add a chain that's not in networks.json?

**Comment by tombeynon** [comment]
This is a very good point! I expected the former to work but clearly didn't test it. I'll try and get a fix out for this later today

**Comment by tombeynon** [comment]
You could add to `src/networks.json` (not networks.local.json) manually in the meantime

**Comment by freak12techno** [comment]
Got it, seems to work, now it says that I'm not an operator, will fix in a bit.

**Comment by freak12techno** [comment]
https://github.com/eco-stake/validator-registry/pull/260 here we go
