### ISSUE TITLE
likecoin setup failed

### ISSUE THREAD

**Issue by freemanhk** [eco-stake/restake#491]
Hi,

I have newly setup operators for BAND and Likecoin (setup in the main branch, FYI) but seems that these 2 networks are not seen in the script output when I run the script manually.

It was reported that my node was not an operator when I try to set it up in networks.local.json.

Please advise if what we can do in my side, or I need to wait the script to be updated so as to use the services.

Thanks.

**Comment by tombeynon** [comment]
If they're not in networks.json you will need to add the key to networks.local.json. 

Otherwise if you're in validator registry it should recognise you. Does the address the script outputs match the one you put in validator registry?

**Comment by freemanhk** [comment]
Okay. Will try to add keys to networks.local.json and see. thanks.
