### ISSUE TITLE
Redelegating on Juno Not Working

### ISSUE THREAD

**Issue by joesixpack** [eco-stake/restake#493]
![image](https://user-images.githubusercontent.com/23145642/167812042-9ecd73a4-d624-4452-b3d7-99f6efae6399.png)

**Comment by tombeynon** [comment]
I need to improve the message but it means you have a redelegation pending. When you redelegate to a validator, you have to wait the unbonding period before you can redelegate again from that same validator. 

You can check your address on Mintscan to see how long is left before it unlocks.
