### ISSUE TITLE
Token Name of the Likecoin Chain should be "LIKE". Now it is shown as ANOLIKE

### ISSUE THREAD

**Issue by freemanhk** [eco-stake/restake#495]
The token name of Likecoin Chain is "LIKE", instead of "ANOLIKE". Please update. I also show the locations of text to be amended attached below for your reference. Thanks.

<img width="1124" alt="Screenshot 2022-05-18 at 23 35 23" src="https://user-images.githubusercontent.com/82752002/169084521-91868606-b26e-4c6d-8995-f57af4fff9ff.png">

**Comment by chleeab** [comment]
I believe restake took the daemon name as nanolike (Which is correct) and the slicing is wrong.
Also, according to this, https://github.com/cosmos/chain-registry/blob/master/likecoin/assetlist.json , restake should able to take the token name LIKE. But can any likecoin validator confirm this? https://github.com/cosmos/chain-registry/blob/master/likecoin/assetlist.json#L14 
Usually it is 6.

**Comment by chleeab** [comment]
Here is the bug: https://github.com/eco-stake/restake/blob/master/src/components/Coins.js#L17-L23
Likecoin daemon is nanolike and token name is LIKE. Which is not the normal convention of cosmos ecosystem token name as the convention is ATOM and uatom.
I suggest the daemon name and decimal point can read from the assetlist from chain registry.

**Comment by freemanhk** [comment]
denom of LikeCoin is nanolike with decimal of 9. The name of the token is LIKE.

**Comment by tombeynon** [comment]
Thanks so much for investigating this @chleeab @freemanhk ❤️
