### ISSUE TITLE
Evmos key generate problem

### ISSUE THREAD

**Issue by AutoStake1** [eco-stake/restake#504]
If I try 
"slip44": 118 or 
"slip44": 60
REStake generates a different address and pubkey compared to if I generate either using evmosd directly

This is causing restake to fail with error:
```
Code: 8; Raw log: pubKey does not match signer address evmos1XYXYX with signer index: 0: invalid pubkey
```

**Comment by tombeynon** [comment]
Yea I quite quickly realised this was still an issue. Difficult to test as I'm not a validator. 

I yanked the update from the UI last night, so Evmos isn't 'live' there yet. I have the solution and will put that in place this evening, so expect an update then that will fix it. 

Keeping this open until it's resolved.

**Comment by BlockNgine** [comment]
Thanks very much :pray:
