### ISSUE TITLE
Failed to broadcast: Request failed with status code 503

### ISSUE THREAD

**Issue by viriava** [eco-stake/restake#530]
I cannot delete a validator with ZERO Delegation.
I can not Enable restacking

Error: Failed to broadcast: Request failed with status code 503

![Google Chrome_2022-06-20 21-45-51@2x](https://user-images.githubusercontent.com/5452240/174669100-40941bc2-4122-43c6-a318-1df319727492.jpg)
![Google Chrome_2022-06-20 21-46-16@2x](https://user-images.githubusercontent.com/5452240/174669108-799c18de-c18a-490d-adbf-2fc7139b5a43.jpg)

**Comment by tombeynon** [comment]
Fix coming for the 0 delegations.

The 503 error means the node was down - could you try again and let me know if that's solved?
