### ISSUE TITLE
Exclude Tgrade

### ISSUE THREAD

**Issue by webmaster128** [eco-stake/restake#562]
https://restake.app/ lists Tgrade which is cool. However, Tgrade does not include the Cosmos SDK staking module. Staking from external delegators is not part of the economic design of the chain. Instead, it uses Proof of Engagement that incentivises engagement. Validators stake to themselves. I think there is no match for Tgrade and this tool any time soon. So I recommend exlcuding Tgrade.

**Comment by tombeynon** [comment]
Awesome thank you for that context! I think Aioz is similar as they don't support the standard validators endpoint.

While I want REStake to be useful for other wallet functions like voting and general Authz management, these don't really support the minimum functionality to be worth keeping. Will PR a removal shortly.
