### ISSUE TITLE
Carbon Framework Error to Restake

### ISSUE THREAD

**Issue by psyscope** [eco-stake/restake#567]
Error when trying to setup auto-staking for Carbon - 

Failed to broadcast: Error when broadcasting tx 69A2799069450AF57CD999CC7B6698DF511D31CCFFB21268ED0394EC113D5465 at height 0. Code: 13; Raw log: insufficient fees; got: 252848swth required: 100000000swth: insufficient fee

**Comment by tombeynon** [comment]
This is either because your wallet didn't have enough balance, or the gasPrices aren't configured correctly for Carbon. Could you tell me if you got this resolved or not?

**Comment by psyscope** [comment]
I think it is Gas Prices aren't configured correctly on carbon.  To enable it Keplr shows me the amount needed. When I accept, it fails. Asking for a lot higher swth.
Keplr states it should be 252848swth  but then fails because they want 100000000swth:

**Comment by tombeynon** [comment]
Gas config is now imported from Chain Registry so many issues like this should be fixed now. I'll close but please reopen if any other problems
