### ISSUE TITLE
Various Issues with Ledger CLI Workaround

### ISSUE THREAD

**Issue by joesixpack** [eco-stake/restake#607]
Agoric:

```
Error: failed to generate ledger key: failed to recover pubkey: [APDU_CODE_DATA_INVALID] Referenced data reversibly blocked (invalidated): address rejected for path m/44'/564'/0'/0/0
```

Cosmoshub (tried different RPCs and gas)::

```
raw_log: 'signature verification failed; please verify account number (880981), sequence
  (25) and chain-id (cosmoshub-4): unauthorized'
```

EVMOS: Not compatible -- is this leftover from months ago?  Ledger is supported now.

Osmosis (tried different RPCs and gas):

```
raw_log: 'signature verification failed; please verify account number (317357), sequence
  (60) and chain-id (osmosis-1): unauthorized'
```

**Comment by joesixpack** [comment]
Rebus:

![image](https://user-images.githubusercontent.com/23145642/193178518-9fbdb185-9ce9-435c-85f8-1650b9299212.png)

**Comment by mbolesta** [comment]
I was able to send the grants for cosmoshub in May, but now I the same thing you do trying to remove the grants. I wonder if it's a bug

**Comment by tombeynon** [comment]
This can now all be done in the UI, even with ledger - closing, please reopen if any other problems
