### ISSUE TITLE
Support for CosmosSDK v0.46

### ISSUE THREAD

**Issue by AutoStake-net** [eco-stake/restake#623]
Hey, I believe since v0.46.x onwards the LCD endpoints have changed

for example `blocks/latest` is now

https://api-umee-ia.cosmosia.notional.ventures/cosmos/base/tendermint/v1beta1/blocks/latest

and the old endpoints is now deprecated which means RESTake is now longer working for the chains that upgrade to the newer SDK chains such as Umee

**Comment by tombeynon** [comment]
I'll have this sorted later today - the necessary updates have been made to cosmos.directory but REStake still needs an update for custom restUrl configs.

**Comment by AutoStake-net** [comment]
Legend!

**Comment by AutoStake-net** [comment]
Hey one of my delegators just tried granting a new address via ledger on umee

https://www.mintscan.io/umee/txs/2160034687CC2C87AAF02B880EF487231D243DFCCA424F01ED0743D7186FF47A

however restake script is not picking it up

it is still working fine for his old non-ledger address though - could this be related to the new endpoints too?

**Comment by tombeynon** [comment]
Looks fine.. the logs should mention their address and the fact it's a generic grant but still allowed. Do you see any mention of their address at all?

The only other cause I can think of would be your node running behind and hadn't picked up the TX with the grant yet.
