### ISSUE TITLE
Invalid pubkey enabling restake on REBUS. Using Kepler and one Evmos compatible wallet.

### ISSUE THREAD

**Issue by jatubio** [eco-stake/restake#632]
I'm trying to enable restake on my REBUS wallet using Kepler and I get this error:

Failed to broadcast: Error when broadcasting tx D60473771D24DA151C39C1295FD940829268CA04462D6A310356CEAE4BE2C832 at height 0. Code: 8; Raw log: pubKey does not match signer address rebus1wk6m... with signer index: 0: invalid pubkey

It's a Evmos compatible wallet so this maybe the problem. Because I have another Keplr with another Rebus 'cosmos only' wallet and made the restake without problems.

**Comment by 18688668** [comment]
yes，i have the same error

**Comment by Farbregas3** [comment]
same

**Comment by ahpoh1349** [comment]
same me too

**Comment by EddieV3** [comment]
Still a problem:
Failed to broadcast: Error when broadcasting tx ACC4A93222EBEBA814C6F85772081CB24F50221D08AD511B6A440A067F5FE395 at height 0. Code: 8; Raw log: pubKey does not match signer address rebus1lte...... with signer index: 0: invalid pubkey

Using Keplr browser extension on Firefox. Have cleared my browser history, cookies, etc.
