### ISSUE TITLE
Gravity Bridge broken after last upgrade

### ISSUE THREAD

**Issue by activenodes** [eco-stake/restake#633]
`Failed with error: Could not connect to REST API`

Tom:
> I guess gravity doesn’t support the ‘new’ block endpoint

**Comment by clemensgg** [comment]
hi, have the same error, also with lumnetwork. tho lum is on sdk 0.45.7

**Comment by tombeynon** [comment]
All sorted in master. Looks like this was affecting Gravity, Lum, Terra and potentially others

**Comment by tombeynon** [comment]
Or not.. lots of endpoints seem to have changed here
