### ISSUE TITLE
Does not work with rebus for me

### ISSUE THREAD

**Issue by goldmembertoha** [eco-stake/restake#640]
I can not enable restake option with error like this "Failed to broadcast: Error when broadcasting tx 41B8C18DDB178DCC0A7668C953B00ABD0B0AE23CDFB5F3A044322A029AD1F614 at height 0. Code: 8; Raw log: pubKey does not match signer address rebus1uyyqxfa7f3fmtaqe2dayztc46dxnqe5ku2rye8 with signer index: 0: invalid pubkey"

**Comment by devil1020** [comment]
Same error coming for me as well!

**Comment by angryolk** [comment]
Failed to broadcast: Error when broadcasting tx A09FA5B510519150B188ED9432F37D8179664E2EE390CA5C97EC34ED5D314304 at height 0. Code: 8; Raw log: pubKey does not match signer address rebus14jh7djy9atd5ftvqqx70yagwelj5lvk6alphfa with signer index: 0: invalid pubkey

**Comment by angryolk** [comment]
same
