### ISSUE TITLE
Can not stake

### ISSUE THREAD

**Issue by MaNat77** [eco-stake/restake#658]
![20221025_202212](https://user-images.githubusercontent.com/116581785/197841269-14af5ae2-7822-438a-8ea8-a2c788fede4b.jpg)

**Comment by MaNat77** [comment]
What can I do with this?

**Comment by tombeynon** [comment]
@MaNat77 REStake wasn't setting the necessary config when adding the chain to Keplr for the first time. This is resolved now, but Keplr will generate a different address for the same private key if you remove and re-add Lambda. I'm not sure how to access any funds sent to the address generated with the incorrect config I'm afraid.
