### ISSUE TITLE
restake jackal

### ISSUE THREAD

**Issue by monika373** [eco-stake/restake#660]
restake doesnt work for jackal

**Comment by tombeynon** [comment]
Can you provide an error message or explain this any more? The only open issue I'm aware of is #638 - do you have account-number of `0` ?

**Comment by Relyte** [comment]
Following up on @monika373's bug report. I noticed my Jackal restake operator wasn't compounding. I get the following error:

```
$ docker-compose run --rm app npm run autostake jackal
Creating restake_app_run ... done

> restake@0.1.0 autostake
> NODE_OPTIONS=--openssl-legacy-provider node scripts/autostake.mjs "jackal"

[20:00:14.456] Invalid network name: jackal
```

I ran the autostake command after ensuring I pulled the latest changes and rebuilt from it. I'm assuming this is what they meant.
