### ISSUE TITLE
DNS To Repo Unresolved

### ISSUE THREAD

**Issue by gaia** [eco-stake/restake#666]
![image](https://user-images.githubusercontent.com/87547/199354883-b9d309e6-211f-48b6-bf0b-f9a001ce9a04.png)

can't update restake. using `git pull && docker-compose run --rm app npm install && docker-compose build --no-cache`

**Comment by tombeynon** [comment]
It sounds like your Docker environment has issues connecting to the internet. The link below might help, or you could use the standard npm installation method in the README and avoid Docker altogether.

https://stackoverflow.com/questions/61567404/docker-temporary-failure-resolving-deb-debian-org

**Comment by gaia** [comment]
thanks, tom. I tried these https://forums.docker.com/t/dns-issues-with-local-resolver-and-containers-on-the-same-host/102319/4, didn't work. restake used to work fine under an older version, and the only thing that has changed with the machine is ipv6 being disabled.

switched to npm. closing w/o resolution.
