### ISSUE TITLE
Failed to get rewards: MEME

### ISSUE THREAD

**Issue by EddieV3** [eco-stake/restake#674]
Getting this error message when switching to MEME network:

Failed to get rewards.

Delegation and wallet balance just spins for a long time, eventually it pulls the amounts but cannot stake. Already have an amount staked.

I have cleared browser history, cookies, etc. Updated to latest Keplr browser extension. Firefox 106.0.5

![Screenshot_2022-11-09_05-58-02](https://user-images.githubusercontent.com/117824267/200819405-0cc1349f-3360-491b-8f3b-c2ccc150153b.png)

**Comment by tombeynon** [comment]
Thank you for raising this - one of the nodes is misbehaving so I've removed it from usual rotation. Should be sorted now - if you see this again, give it 10 mins and try again.
