### ISSUE TITLE
Enabling canto fails during gas estimation with provided fee < minimum global fee 

### ISSUE THREAD

**Issue by joeabbey** [eco-stake/restake#702]
After clicking "Enable REStake"

```
`Failed to broadcast: rpc error: code = Unknown desc = provided fee < minimum global fee (2500000000000000acanto < 100000000000000000acanto). Please increase the gas price.: insufficient fee [evmos/ethermint@v0.19.3/app/ante/fees.go:65] With gas wanted: '0' and gas used: '15442' : unknown request
```
Recently canto passed a gov proposal bumping the feemarket to 10000 gwei and then stepping down a bit to 1000gwei.

I'm going to update chain-registry... but not sure if there's something else that needs modification for restake.

**Comment by joeabbey** [comment]
I suppose for canto we could set `"gasPricePrefer": "1000000000000acanto"`

**Comment by tombeynon** [comment]
@joeabbey gas config is now imported from Chain Registry so issues like this should be fixed now. I'll close but please reopen if any other problems
