### ISSUE TITLE
restake.app unstaking

### ISSUE THREAD

**Issue by mktk20102012** [eco-stake/restake#706]
I unstaked my plq (and revoked the grant) at restake.app but it hasn't been added to my balance in my keplr wallet. In my keplr wallet it says that it is still staked but it doesn't show it anymore on restake.app; if anyone could point me in the right direction would be very much appreciated.

**Comment by tombeynon** [comment]
@mktk20102012 it takes 21 days to unstake on most networks. REStake doesn't show the unbonding tokens currently, but you can see it on most explorers like https://explorer.planq.network/ (search for your address).

This will be added to REStake in the future
