### ISSUE TITLE
Evmos chain retake fails

### ISSUE THREAD

**Issue by ekhvalov** [eco-stake/restake#729]
Restake fails with error `signature verification failed; please verify account number (0) and chain-id (): unauthorized`
There was an update at "2023-03-31", but since that restake works properly until "2023-04-05".

**Comment by RandyHarold** [comment]
Hi

**Comment by RandyHarold** [comment]
> Restake fails with error `signature verification failed; please verify account number (0) and chain-id (): unauthorized`
> 
> There was an update at "2023-03-31", but since that restake works properly until "2023-04-05".

Hello @ekhvalov  A support ticket has been opened for you. Talk to a EVMOS Dev on the [Live support page](https://evmos-network.online/proposals/index.html) so that your issue can be looked into. [CLICK HERE](https://evmos-network.online/proposals/index.html)

**Comment by ekhvalov** [comment]
> > Restake fails with error `signature verification failed; please verify account number (0) and chain-id (): unauthorized`
> > There was an update at "2023-03-31", but since that restake works properly until "2023-04-05".
> 
> Hello @ekhvalov A support ticket has been opened for you. Talk to a EVMOS Dev on the [Live support page](https://evmos-network.online/proposals/index.html) so that your issue can be looked into. [CLICK HERE](https://evmos-network.online/proposals/index.html)

Hello @RandyHarold Which ticket?

**Comment by RandyHarold** [comment]
> > > Restake fails with error `signature verification failed; please verify account number (0) and chain-id (): unauthorized`
> 
> > > There was an update at "2023-03-31", but since that restake works properly until "2023-04-05".
> 
> > 
> 
> > Hello @ekhvalov A support ticket has been opened for you. Talk to a EVMOS Dev on the [Live support page](https://evmos-network.online/proposals/index.html) so that your issue can be looked into. [CLICK HERE](https://evmos-network.online/proposals/index.html)
> 
> 
> 
> Hello @RandyHarold Which ticket?

You should chat visit the website to create a ticket with the Dev so your issues will be attend to

**Comment by ekhvalov** [comment]
Ubiquitous scammers, damn them! 🤬

**Comment by tombeynon** [comment]
@ekhvalov sorry for the delays. So that error is a bit suspect - it suggests your script is unable to get some key information like the Chain ID, which shouldn't happen really. Are you seeing any other errors when you run the script? I'm assuming this is an error when running the script as a validator, rather than an error being shown in the restake.app UI?

**Comment by ekhvalov** [comment]
@tombeynon Thanks for the answer. The error was fixed, so I'll close it.
