### ISSUE TITLE
`src/networks.json` - Question about running the script

### ISSUE THREAD

**Issue by vchong** [eco-stake/restake#744]
1. All the `ownerAddress`s in `src/networks.json` belong to Eco-stake?
2. Do i have to replace all the `ownerAddress`s in `src/networks.json` with my own before running the script?

Thanks

**Comment by tombeynon** [comment]
@vchong you don't need to change that - it's actually unused now, it's left over from when the UI code was also in this repository, and defined which validator appeared at the top of the list on restake.app. It's not used at all for the REStake autostaking script and I'll remove it when I get a chance.

**Comment by tombeynon** [comment]
Just need to submit to validator registry, that's where it gets that info from. networks.local.json is for adjusting gas prices, timeouts etc.
