### ISSUE TITLE
Not checking all delegators for grants

### ISSUE THREAD

**Issue by atlas-eric** [eco-stake/restake#752]
Latest version.

On kava with over 500 delegators
The amount of delegators checked is seldom over 50 max 200 in several tests.

HOW TO: force checking larger nr of delegators?

Bot balance is 1797993 ukava
Finding delegators...
...batch 1
...batch 2
Checking 50 delegators for grants...
...batch 1
Found 0 addresses with valid grants...
Sent 0/0 transactions

Settings: (tried different values without success)

      "retries": 3,
      "batchPageSize": 50,
      "batchQueries": 10,
      "batchTxs": 50,
      "delegationsTimeout": 20000,
      "queryTimeout": 5000,
      "queryThrottle": 100,
      "gasModifier": 1.1,
      "correctSlip44": true

**Comment by thejoven** [comment]
I also noticed this problem, have you solved it?

[10:30:12.029] Checking 227 delegators for grants...
[10:30:12.326] ...batch 1
[10:30:12.429] Found 0 addresses with valid grants...
[10:30:12.430] Sent 0/0 transactions
[10:30:12.430] Autostake completed after 1 attempt(s)
[10:30:12.431] Attempt 1:
[10:30:12.431] Sent 0/0 transactions
[10:30:12.431] Autostake finished

**Comment by atlas-eric** [comment]
> I also noticed this problem, have you solved it?
> 
No, it looks like it checks a random number of delegators. Every now and then its enough to process them all

**Comment by tombeynon** [comment]
@atlas-eric strange - are you using your own node or the default public ones? Some of the public nodes behave strangely sometimes, I suspect certain endpoints are like validator delegations are often blocked.

**Comment by atlas-eric** [comment]
@tombeynon 
I am not aware of pointing to our node.
Chances are I missed that setting/optimisation.
( chains.json ? )

**Comment by atlas-eric** [comment]
@thejoven 

Thanks for the insight
After changing the rest url in the file:  "networks.local.json" to:

"restUrl": [
            "https://kava-rest.publicnode.com"
 ],

Processing KAVA went from slow to instant and worked.
