### ISSUE TITLE
Evmos Failed with error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by thejoven** [eco-stake/restake#757]
docker-compose run --rm app npm run autostake evmos
Creating restake_app_run ... done

> restake@0.1.0 autostake
> node scripts/autostake.mjs "evmos"

[14:14:41.427] ⚛
[14:14:43.173] Loaded evmos
[14:14:43.173] Found ETH coin type
[14:14:43.174] Using HD Path m/44'/60'/0'/0/0
[14:14:43.245] Failed with error: error:0308010C:digital envelope routines::unsupported
[14:14:43.245] Failed attempt 1/3, retrying in 30 seconds...
^Cnpm notice 
npm notice New major version of npm available! 8.11.0 -> 10.2.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.2.3
npm notice Run npm install -g npm@10.2.3 to update!
npm notice 
npm ERR! path /usr/src/app
npm ERR! command failed
npm ERR! signal SIGINT
npm ERR! command sh -c node scripts/autostake.mjs "evmos"

**Comment by tombeynon** [comment]
I seem to recall this being a node version issue - can you try `docker-compose build` to ensure you've built the latest version?

**Comment by thejoven** [comment]
> I seem to recall this being a node version issue - can you try `docker-compose build` to ensure you've built the latest version?
Thank you for your assistance, normal operation has been restored after rebuilding.
