### ISSUE TITLE
Same restake address multiple times, no transactions processed

### ISSUE THREAD

**Issue by atlas-eric** [eco-stake/restake#762]
Somehow a delegator got registered 3 times for restake, 
Could this be the reason no restakes transactions are triggered although the address is found and the parameters for restake are OK?
The restake value is ~ 11x times the treshold.

Dec 01 11:02:01 100-atlas-mngmt docker[211705]: [11:02:01.435] Checking 567 delegators for grants...
Dec 01 11:02:01 100-atlas-mngmt docker[211705]: [11:02:01.512] ...batch 1
Dec 01 11:02:01 100-atlas-mngmt docker[211705]: [11:02:01.619] Found 4 addresses with valid grants...
Dec 01 11:02:01 100-atlas-mngmt docker[211705]: [11:02:01.620] Calculating and autostaking in batches of 50
Dec 01 11:02:01 100-atlas-mngmt docker[211705]: [11:02:01.760] kava1-delegator-address Can autostake 1196842 ukava
Dec 01 11:02:01 100-atlas-mngmt docker[211705]: [11:02:01.781] kava1-other-delegator-address Can autostake 1017564 ukava
Dec 01 11:02:01 100-atlas-mngmt docker[211705]: [11:02:01.791] kava1-delegatoraddress Can autostake 1196842 ukava
Dec 01 11:02:01 100-atlas-mngmt docker[211705]: [11:02:01.826] kava1-delegatoraddress Can autostake 1196842 ukava
Dec 01 11:02:01 100-atlas-mngmt docker[211705]: [11:02:01.830] Sent 0/0 transactions
Dec 01 11:02:01 100-atlas-mngmt docker[211705]: [11:02:01.831] Autostake completed after 1 attempt(s)
Dec 01 11:02:01 100-atlas-mngmt docker[211705]: [11:02:01.832] Attempt 1:
Dec 01 11:02:01 100-atlas-mngmt docker[211705]: [11:02:01.833] Sent 0/0 transactions
Dec 01 11:02:01 100-atlas-mngmt docker[211705]: [11:02:01.834] Autostake finished

**Comment by tombeynon** [comment]
The duplicate addresses should be fixed in the latest version (v2.12.0) on master. Please try updating and see if that sorts it.
