### ISSUE TITLE
Refactoring: use proper logging solution

### ISSUE THREAD

**Issue by freak12techno** [eco-stake/restake#779]
Would be nice if REStake would use the logging solution instead of `timestamp(...)`. My suggestion is [winston](https://github.com/winstonjs/winston).

Benefits:
1) possibility to display logs in one format instead of needing to have custom helpers to format logs
2) ability to create subloggers (e.g. there can be main logger and each NetworkRunner can have a sublogger with `{ chain: <chain_name> }` and inside all logs would have `chain=<chain_name>` prepended
3) all logging is done via structured entries that include not only the timestamp, but some data (see the point above)
4) ability to log into JSON (extra useful for those viewing logs via external logging solutions, like me lol), colored logs etc.

Also feel free to assign me to this, I have an idea on how to make it possible.

**Comment by freak12techno** [comment]
Just noticed it basically duplicates #734, but with more context.

**Comment by tombeynon** [comment]
@freak12techno Completely agree this is needed and has been requested a few times. It would be amazing if you could take a look, otherwise I'll prioritise. Thanks so much!
