### ISSUE TITLE
Keplr address doesn't match autostaking script address

### ISSUE THREAD

**Issue by tombeynon** [eco-stake/restake#78]
Had reports of this for Desmos, maybe others. When your autostaking mnemonic is imported into Keplr, the address matches for most networks but some it does not. E.g. Desmos.

For the purpose of running the script, the address spat out by `npm run autostake` is the correct one. This is the one you should fund and the script will send TXs from. I'm not sure how to actually access this in Keplr as of writing but it's probably derivation path related.

If you see this on any other networks, please add to this issue. I'll put a note in the README asap.

**Comment by chleeab** [comment]
I remeber I saw something like Desmos use another derivation path. But can't find it now.

**Comment by tombeynon** [comment]
Hmm we have everything we need to solve this now, as all chain registry data is available in the application. I think unfortunately we just have to break things here, but an operator can always override the slip44 path in `networks.local.json` if they want to continue supporting the old format as well.

I'll make sure this is mentioned in the README, and it will be clear enough to users in the UI if they need to 're-grant' to the validator.

I'll look to get a fix out for this ASAP to minimise how many grants are created against the wrong addresses

**Comment by poorbuthappy** [comment]
Is there any example I can follow for networks.local.json which handle bitsong issue please?

**Comment by tombeynon** [comment]
There's not really an issue, just fund the address the script gives you when you run it and use that as your botAddress. You just can't use it in Keplr and it's non-standard. The bot address should be a hot wallet + not heavily funded, so I believe it's workable in the meantime.

**Comment by poorbuthappy** [comment]
Thanks Tombeynon, will have a try ..

**Comment by freemanhk** [comment]
Desmos and Bitsong are using different coin types (Desmos is 852 and Bitsong is 639) from Cosmos, which is 118. Currently tools generating wallets for Bitsong and Desmos, including CLI and Keplor are using new coin types which will generate different wallet address from bot address. (I dont serve Persistence but seem facing the same situations)

**Comment by tombeynon** [comment]
@poorbuthappy see #304
