### ISSUE TITLE
restake.app terra classic issue

### ISSUE THREAD

**Issue by ofirielon** [eco-stake/restake#781]
cant active restake it claims eror code 429 on terra classic and kava all others works perfectly so far!

**Comment by tombeynon** [comment]
This should be better now - there were some public nodes with strict rate limiting that were causing issues. Please re-open if you continue to experience this.

**Comment by ofirielon** [comment]
original problem fixed! now i face a new one.it says:"|Failed to broadcast: Unable to sign message with this wallet/signer"
i have a ledger hardware wallet and it works for all other suported coins perfectly...
