### ISSUE TITLE
Failed to broadcast: Unable to sign message with this wallet/signer

### ISSUE THREAD

**Issue by navarika** [eco-stake/restake#783]
Keplr with connect hardware wallet (Ledger)

<img width="440" alt="enable_restake_2024-06-14 121225" src="https://github.com/eco-stake/restake/assets/44608181/6c47772b-7636-4e61-a056-e06f44857a51">

**Comment by tombeynon** [comment]
Fixed in https://github.com/eco-stake/restake-ui/pull/102
