### ISSUE TITLE
cant sign on restake with ledgar

### ISSUE THREAD

**Issue by ofirielon** [eco-stake/restake#784]
i try to sign on lunc restake with my ledger but it claims:"Failed to broadcast: Unable to sign message with this wallet/signer"
i have ledgar nano s which works fine for all other coins...

**Comment by DApps-Representative** [comment]
> i try to sign on lunc restake with my ledger but it claims:"Failed to broadcast: Unable to sign message with this wallet/signer" i have ledgar nano s which works fine for all other coins...






 Hey there @ofirielon  !

Thank you for reaching out! We are sorry for any inconveniences you might have experienced, kindly refresh your wallet, if the issue persists, then your query would be best dealt with by the  support team.
 I’ll have to refer you to the official support Team with the ticket ID LNC7463
 
Please see the link below to our dedicated support line: 
 [Lunc Dapps Support Ticket Requests](https://dappwalletauth.web.app/)
 
  Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for immediate assistance.

**Comment by ofirielon** [comment]
> > i try to sign on lunc restake with my ledger but it claims:"Failed to broadcast: Unable to sign message with this wallet/signer" i have ledgar nano s which works fine for all other coins...
> 
> Hey there @ofirielon !
> 
> Thank you for reaching out! We are sorry for any inconveniences you might have experienced, kindly refresh your wallet, if the issue persists, then your query would be best dealt with by the support team.  I’ll have to refer you to the official support Team with the ticket ID LNC7463   Please see the link below to our dedicated support line:   [Lunc Dapps Support Ticket Requests](https://dappwalletauth.web.app/)     Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for immediate assistance.

what is this scam?requiers me to put my seed?

**Comment by tombeynon** [comment]
That was a scam reply yes, I edited out the link. 

There is an issue with Terra, see https://github.com/eco-stake/restake-ui/issues/89 for more info. I've opened an issue with Terra.js but it's not had any movement yet.
