### ISSUE TITLE
Sentinel hub can't load grants

### ISSUE THREAD

**Issue by LoulouCrypto** [eco-stake/restake#787]
I can't load grants from Sentinel hub chain 
I try with personal rest server but nothing 
I have this error : 
Failed with error: Failed to load grants: undefined module=health

**Comment by tombeynon** [comment]
Strange, does it always throw that error? Are you using `sentinelhub` as the chain name? And is the REST API accessible to the restake script?

**Comment by LoulouCrypto** [comment]
Hm no it don't make the error every times 
i put sentinel as name ... i try sentinelhub

**Comment by LoulouCrypto** [comment]
ok in chain registery it's know as sentinel 
i connect to the REST API all good but the bug is when it try to collect grant

**Comment by roomit-xyz** [comment]
[2024-08-20T16:28:16.440Z] info: Failed with error: Failed to load grants: undefined module=health
[2024-08-20T16:28:16.441Z] info: Failed attempt 1/3, retrying in 30 seconds... module=health

I think this bugs, always like that when grants

**Comment by tombeynon** [comment]
It looks like the request is timing out often, even with a page size of 1. Sometimes the request will succeed but return no grants. Other times it responds correctly.

Aside from using your own REST API, the only other suggestion would be reducing the `batchPageSize` config mentioned in the docs and see if that helps.

There's not much else we can do about this, I'm not sure why it's affecting Sentinel so badly but I would suggest raising with the team over there to see if there's an issue in their code. 

The request we use is e.g.: `https://rest.cosmos.directory/sentinel/cosmos/authz/v1beta1/grants/grantee/{botAddress}?pagination.limit=100`
