### ISSUE TITLE
Calculate APY

### ISSUE THREAD

**Issue by jemrickrioux** [eco-stake/restake#80]
Add a feature to calculate APY and show them in the UI

**Comment by jemrickrioux** [comment]
#87 Here is my PR :)

**Comment by jemrickrioux** [comment]
Let me know if you need me to restructure my code or if I need to code things differently. TBH it's the first open source project I'm contributing to 😄

**Comment by tombeynon** [comment]
This is so incredible, and PR is perfect. Will be getting this merged in asap asap

**Comment by jemrickrioux** [comment]
#215 We ready

**Comment by tombeynon** [comment]
Completed in #215 and #254
